valor = input("Digite algo: ")
print("O tipo primitivo desse valor é: ", type(valor))
print("Esse valor só tem espaços: ", valor.isspace())
print("Esse valor é numérico: ", valor.isnumeric())
print("Esse valor é alfabético: ", valor.isalpha())
print("Esse valor é alfanumérico: ", valor.isalnum())
print("Esse valor é um número: ", valor.isnumeric())
print("Esse valor é maiúsculo: ", valor.isupper())
print("Esse valor é minúsculo: ", valor.islower())
